version: "3"
services:
  postgres:
    container_name: postgres
    restart: unless-stopped
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: api-user
      POSTGRES_DB: api-db
    volumes:
      - data-db:/var/lib/postgresql/data/
    networks:
      - api
volumes:
  data-db:

networks:
  api:
    name: Api
    driver: bridge
