version: "3"
services:
  postgres:
    container_name: api-postgres
    restart: unless-stopped
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    env_file: .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: api-user
      POSTGRES_DB: api-db
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    networks:
      - internal
volumes:
  postgres-data:

networks:
  internal:
    name: internal
    driver: bridge
